title: Priya Bhatnagar # your name (or website title) here
logo: "/images//IMG_9935_Facetune_04-08-2021-11-31-09.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a senior at Lehigh Universty with an expected graduation of May 2022. I am learning data analytics to understand the finance industry better. 
  <br><br>
  BS Finance
  <br><br>
  <a href="https://www.linkedin.com/in/priya-bhatnagar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
